name: az-cli setup for OIDC 
on:
 workflow_dispatch:
  
# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: write    # This is required for actions/checkout@v1

jobs:
  azcli-install:
    runs-on: ubuntu-latest
    steps:
   
      - name: Git clone the repository
        uses: actions/checkout@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Install Azure CLI
        run: |
         az --version
         python -m venv env
         source env/bin/activate
         sudo apt install gcc python3-dev
         pip install azdev
         pwd
         azdev setup --cli .
         az --version

      # Following section fetches OIDC token from provider
      - uses: actions/setup-node@v2
      - run: npm install @actions/core@1.6.0-beta.0 
      - name: Get OIDC id token
        uses: actions/github-script@v4
        id: idtoken
        with:
        # Audience field is optional. By default, the value is the repo's url. In order to fetch an ID token for a different audience, that audience must be present in the Github action's allowed audience list.
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken('api://AzureADTokenExchange') 
            coredemo.setOutput('id_token', id_token)
    
       # You can use the OIDC Id_token retrieved in step above using steps.idtoken.outputs.id_token and pass to AzCli to fetch access token
      - name: Use installed azure cli tool
        run: |
         source env/bin/activate
         az --version
         echo ${{ steps.idtoken.outputs.id_token }}


      # Following steps are just for reference purpose to fetch Access token via OIDC token
      # This step fetches access token, do update <cliend_Id> used below with your own.
      - name: Get Access Token
        id: accessToken
        run: |
          big_json=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'client_id=<client_Id>&scope=https://graph.microsoft.com/.default&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=${{ steps.idtoken.outputs.id_token }}&grant_type=client_credentials' 'https://login.microsoftonline.com/55d2ac9d-9289-4a54-9cc7-47222a96a7fa/oauth2/v2.0/token?dc=ESTS-PUB-WUS2-AZ1-FD000-TEST1')
          big_json="${big_json//'%'/'%25'}"
          big_json="${big_json//$'\n'/'%0A'}"
          big_json="${big_json//$'\r'/'%0D'}"
          echo "::set-output name=big_json::$big_json"
          echo $big_json        
        
        # This step makes sample graph API call with Access token retrieved in step above, to validate access token. 
      - name: Graph Api Call using Access Token
        run: |
          big_json=$(curl -X GET -H "Authorization: Bearer ${{fromJson(steps.accessToken.outputs.big_json).access_token}}" -H "Content-Type: application/json" https://graph.microsoft.com/v1.0/users/adfadadb-5d97-4fbd-aad3-0f097138f199/identities)
          big_json="${big_json//'%'/'%25'}"
          big_json="${big_json//$'\n'/'%0A'}"
          big_json="${big_json//$'\r'/'%0D'}"
          echo "::set-output name=big_json::$big_json"
          echo $big_json
